CREATE TABLE [dbo].[User]
(
	[Id] VARCHAR(128) NOT NULL PRIMARY KEY, 
	[FirstName] NVARCHAR(50) NOT NULL, 
    [LastName] NVARCHAR(50) NOT NULL, 
    [EmailAddress] NVARCHAR(256) NOT NULL, 
    [CreateDate] DATETIME2 NOT NULL DEFAULT getUTCDate(),

)
